import numberWithZero from "./numberWithZero.js";
import preloader from "./preloader.js";
import navMenuTabs from "./navMenuTabs.js";
import bannerSlider from "./bannerSlider.js";
import customVimeoPlayer from "./customVimeoPlayer.js";
import alternateDataSrcLoad from "./alternateDataSrcLoad.js";
import videoZoomGSAP from "./videoZoomGSAP.js";
import qrPhoneMovementGSAP from "./qrPhoneMovementGSAP.js";
numberWithZero();
preloader();
navMenuTabs();
bannerSlider();
customVimeoPlayer();
alternateDataSrcLoad();
videoZoomGSAP();
qrPhoneMovementGSAP();
